// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2x0ogPGSr-tNekhgYQ8LsTNfLnMEyJiI',
    appId: '1:296535404143:web:10e904e00ea950ba47a79a',
    messagingSenderId: '296535404143',
    projectId: 'my-notes-vlad-flutter',
    authDomain: 'my-notes-vlad-flutter.firebaseapp.com',
    storageBucket: 'my-notes-vlad-flutter.appspot.com',
    measurementId: 'G-PTVVXFK9PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GERCNDLrj33LPMKQEdbop6orVShOmkU',
    appId: '1:296535404143:android:6224624c551df55047a79a',
    messagingSenderId: '296535404143',
    projectId: 'my-notes-vlad-flutter',
    storageBucket: 'my-notes-vlad-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRRdMNjkcOd8pXIiqrUg8mndNRpXAXfc',
    appId: '1:296535404143:ios:c064d19e77c2404347a79a',
    messagingSenderId: '296535404143',
    projectId: 'my-notes-vlad-flutter',
    storageBucket: 'my-notes-vlad-flutter.appspot.com',
    iosClientId: '296535404143-unrn67oh0b09ers7uli3avmd65ojsagk.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiRRdMNjkcOd8pXIiqrUg8mndNRpXAXfc',
    appId: '1:296535404143:ios:c064d19e77c2404347a79a',
    messagingSenderId: '296535404143',
    projectId: 'my-notes-vlad-flutter',
    storageBucket: 'my-notes-vlad-flutter.appspot.com',
    iosClientId: '296535404143-unrn67oh0b09ers7uli3avmd65ojsagk.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthHub',
  );
}
